'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm4

    '''<summary>
    '''imgHeroBackground control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgHeroBackground As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''litHeroTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litHeroTitle As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litHeroDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litHeroDescription As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litStoryTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litStoryTitle As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litStoryContent1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litStoryContent1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litStoryContent2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litStoryContent2 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lblServicesTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblServicesTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblServicesSubtitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblServicesSubtitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblService1Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblService1Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblService1Desc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblService1Desc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblService2Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblService2Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblService2Desc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblService2Desc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblService3Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblService3Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblService3Desc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblService3Desc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblService4Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblService4Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblService4Desc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblService4Desc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblService5Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblService5Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblService5Desc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblService5Desc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblService6Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblService6Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblService6Desc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblService6Desc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalVehicles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalVehicles As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVehiclesLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVehiclesLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalCustomers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalCustomers As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCustomersLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomersLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalBookings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalBookings As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBookingsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBookingsLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRating control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRating As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRatingLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRatingLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTeamTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeamTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTeamSubtitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeamSubtitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgTeam1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgTeam1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblTeam1Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeam1Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTeam1Position control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeam1Position As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTeam1Description control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeam1Description As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgTeam2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgTeam2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblTeam2Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeam2Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTeam2Position control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeam2Position As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTeam2Description control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeam2Description As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgTeam3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgTeam3 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblTeam3Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeam3Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTeam3Position control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeam3Position As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTeam3Description control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeam3Description As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblContactTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContactTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblContactSubtitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContactSubtitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLocationTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLocationTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''litLocationAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litLocationAddress As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lblContactDetailsTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContactDetailsTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''litContactDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litContactDetails As Global.System.Web.UI.WebControls.Literal
End Class
