'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm13

    '''<summary>
    '''pnlMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMessage As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMakeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMakeName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvMakeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvMakeName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCountry As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMakeDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMakeDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnAddMake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddMake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnUpdateMake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateMake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelMake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelMake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hfSelectedMakeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSelectedMakeID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtSearchMake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchMake As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSearchMake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchMake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnResetMake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResetMake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvMakes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvMakes As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ddlMake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMake As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvMake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvMake As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtModelName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModelName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvModelName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvModelName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtYear As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlFuelType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFuelType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlTransmission control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTransmission As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtSeatingCapacity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSeatingCapacity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtModelDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModelDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnAddModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddModel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnUpdateModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateModel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelModel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hfSelectedModelID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSelectedModelID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ddlSearchMake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSearchMake As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtSearchModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchModel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlSearchFuel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSearchFuel As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnSearchModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchModel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnResetModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResetModel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvModels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvModels As Global.System.Web.UI.WebControls.GridView
End Class
